-- Schema for the Spring Boot rewrite. Runs on PostgreSQL and on H2 in PostgreSQL mode.
-- Never edit a migration that already ran somewhere: add V2__..., V3__... instead.

create table categories (
    id   bigint generated by default as identity primary key,
    name varchar(80) not null unique
);

create table products (
    id          bigint generated by default as identity primary key,
    name        varchar(120)   not null,
    description varchar(1000),
    price       numeric(12, 2) not null check (price > 0),
    stock       integer        not null check (stock >= 0),
    image_url   varchar(255),
    category_id bigint references categories (id),
    version     bigint
);

create table users (
    id    bigint generated by default as identity primary key,
    name  varchar(100) not null,
    email varchar(150) not null unique,
    role  varchar(20)  not null
);

create table orders (
    id         bigint generated by default as identity primary key,
    user_id    bigint                      not null references users (id),
    status     varchar(20)                 not null,
    total      numeric(12, 2)              not null,
    created_at timestamp(6) with time zone not null
);

create table order_lines (
    id           bigint generated by default as identity primary key,
    order_id     bigint         not null references orders (id),
    product_id   bigint         not null references products (id),
    product_name varchar(120)   not null,
    unit_price   numeric(12, 2) not null,
    quantity     integer        not null check (quantity > 0)
);

-- Foreign keys are not indexed automatically in PostgreSQL
create index idx_products_category on products (category_id);
create index idx_orders_user on orders (user_id);
create index idx_order_lines_order on order_lines (order_id);
create index idx_order_lines_product on order_lines (product_id);
